CHAINS = {
    "gongcha": {
        "name": "ゴンチャ",
        "color": "#E85D27",
        "icon": "circle",
        "url": "https://www.gong-cha-jp.com/stores/",
    },
    "crisp": {
        "name": "クリスプサラダワークス",
        "color": "#4CAF50",
        "icon": "circle",
        "url": "https://crisp.tokyo/stores/",
    },
    "withgreen": {
        "name": "withgreen",
        "color": "#2196F3",
        "icon": "circle",
        "url": "https://store.withgreen.club/",
    },
    "deandeluca": {
        "name": "ディーン&デルーカ",
        "color": "#9C27B0",
        "icon": "circle",
        "url": "https://www.deandeluca.co.jp/shop/pages/stores.aspx",
    },
}

CHAIN_IDS = list(CHAINS.keys())
CHAIN_NAMES = {k: v["name"] for k, v in CHAINS.items()}
CHAIN_COLORS = {k: v["color"] for k, v in CHAINS.items()}

AREA_MAP = {
    "北海道": "北海道・東北",
    "青森県": "北海道・東北",
    "岩手県": "北海道・東北",
    "宮城県": "北海道・東北",
    "秋田県": "北海道・東北",
    "山形県": "北海道・東北",
    "福島県": "北海道・東北",
    "茨城県": "関東",
    "栃木県": "関東",
    "群馬県": "関東",
    "埼玉県": "関東",
    "千葉県": "関東",
    "東京都": "関東",
    "神奈川県": "関東",
    "新潟県": "中部",
    "富山県": "中部",
    "石川県": "中部",
    "福井県": "中部",
    "山梨県": "中部",
    "長野県": "中部",
    "岐阜県": "中部",
    "静岡県": "中部",
    "愛知県": "中部",
    "三重県": "近畿",
    "滋賀県": "近畿",
    "京都府": "近畿",
    "大阪府": "近畿",
    "兵庫県": "近畿",
    "奈良県": "近畿",
    "和歌山県": "近畿",
    "鳥取県": "中国・四国",
    "島根県": "中国・四国",
    "岡山県": "中国・四国",
    "広島県": "中国・四国",
    "山口県": "中国・四国",
    "徳島県": "中国・四国",
    "香川県": "中国・四国",
    "愛媛県": "中国・四国",
    "高知県": "中国・四国",
    "福岡県": "九州・沖縄",
    "佐賀県": "九州・沖縄",
    "長崎県": "九州・沖縄",
    "熊本県": "九州・沖縄",
    "大分県": "九州・沖縄",
    "宮崎県": "九州・沖縄",
    "鹿児島県": "九州・沖縄",
    "沖縄県": "九州・沖縄",
}

PREFECTURES = list(AREA_MAP.keys())

CSV_COLUMNS = [
    "chain_id",
    "chain_name",
    "store_id",
    "store_name",
    "address_raw",
    "prefecture",
    "city",
    "open_date",
    "close_date",
    "lat",
    "lng",
    "floor",
    "building",
    "source_url",
    "scraped_at",
]
